// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvugguwnmthhaazfktki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2dWdndXdubXRoaGFhemZrdGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTkyODUsImV4cCI6MjA2NzM3NTI4NX0.7NVR49vNRMkGpvdI8pGP-Jy-b6-T7Imczq-gv8cELyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});